---
title: "GPER"
output: rmarkdown::html_vignette
vignette: Group Penalized Expectile Regression in R A VIGNETTE
  %\VignetteIndexEntry{GPER}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
knitr::opts_knit$set(global.par = TRUE)
knitr::opts_chunk$set(fig.width = 7, fig.height = 4)
```
# Installation

Like many other R packages, the simplest way to obtain GPER is to install it  from github. Type the following command in R console:

```{r setup}
library(devtools)
devtools::install_github("https://github.com/ouhourane/GPER.git")
library(GPQR)
```


```{r Birthwt}
library(grpreg)
data(Birthwt)
x <- Birthwt$X
group <- Birthwt$group
y <- Birthwt$bwt
group <- c(1,1,1,2,2,2,3,3,4,5,5,6,7,8,8,8)
bs <- sqrt(as.integer(as.numeric(table(group))))
tracer_GPER <- function(taux){
  cv <- cv.gper(x=x,y=y,group=group,method="GLasso",tau=taux,eps=0.0001)
  matplot(cv$lambda,t(cv$gper.fit$beta),ylim=c(-0.5,0.5),ylab = expression(beta),
          xlab = expression(lambda),type="l",main=paste("GPER  ",expression(tau) ,
                                                        " = ",taux),col=c(1,1,1,1,1,1,3,3,4,1,1,1,2,1,1,1))
  abline(h=0,col=1); abline(v=cv$lambda.1se,col=1,lty=2)
}
par(mfrow = c(1, 3))
tracer_GPER(0.2)
tracer_GPER(0.5)
tracer_GPER(0.8)
#######################
tracer_COGPER<- function(taux){
  cv2 <- cv.cogper(x=x,y=y,group=group,pf.scale = bs,method="GLasso",tau=taux,w=0.3)
  matplot(cv2$lambda,t(cv2$cogper.fit$beta),ylim=c(-0.5,0.5),ylab = expression(beta),
          xlab = expression(lambda),type="l",main=paste("COGPER  ",expression(taux)," = ",taux),col=c(1,1,1,1,1,1,3,3,4,1,1,1,2,1,1,1))
  abline(h=0,col=1); abline(v=cv2$lambda.1se,col=1,lty=2)
  matplot(cv2$lambda, t(cv2$cogper.fit$theta),ylim=c(-0.1,0.1),ylab = expression(phi),
          xlab = expression(lambda),main=paste("COGPER  ",expression(taux)," = ",taux),type="l",col=c(1,1,1,1,1,1,3,3,4,1,1,1,2,1,1,1))
  abline(h=0,col=1);abline(v=cv2$lambda.1se,col=1,lty=2)
}
par(mfrow = c(2, 3))
tracer_COGPER(0.2)
tracer_COGPER(0.5)
tracer_COGPER(0.8)
```

```{r illustrationCOGPER}
library("MASS")
library(GPER)
library(splines)
par(mfrow = c(2, 2))
xlm=c(-1.5,2)
xlm1=c(-0.5,0.5)
ng=5

group <- rep(1:ng,each=3)
n=300;p=length(group);
betac1=c(rep(2,3),rep(-1,3),rep(0,3),rep(0,p-9))
betac2=c(rep(2,3),rep(-1,3),rep(1,3),rep(0,p-9))
cc1=c(1,2,3);cc2=c(4,5,6);cc3=c(7,8,9);cc4=c(10:p);
sig=1
Xtrain=NULL;
set.seed(1)
for(i in 1:ng) Xtrain=cbind(Xtrain,bs(runif(n),df=3))
####### model 1
Ytrain<-Xtrain%*%betac1 + (pnorm(Xtrain[,7]+Xtrain[,8]+Xtrain[,9]))*rnorm(n,0,sig)
#################################################################################
trace_GPER_illustr <- function(taux,model){
  cv <- cv.gper(x=Xtrain,y=Ytrain,group=group,method="GLasso",tau=taux)
  beta=t(cv$gper.fit$beta)
  seqLambdaGL=cv$lambda
  matplot(seqLambdaGL,beta[,cc1], type = "l",col = 3,lty = 1,ylim=xlm,lwd=1,ylab="Coefficients",
          main=paste("GPER   ",expression(tau),"=",taux," model=",model),xlab = expression(lambda))
  matlines(seqLambdaGL,beta[,cc2], type = "l",col = 2,lty = 1,lwd=1)
  matlines(seqLambdaGL,beta[,cc3], type = "l",col = 4,lty = 1,lwd=1)
  matlines(seqLambdaGL,beta[,cc4], type = "l",col = 1,lty = 1,lwd=1)
  text(0.5,0.5,expression("G"[3]),col=4,cex=1)
  abline(v=cv$lambda.min,lty=2)
}
trace_GPER_illustr(0.5,1)
trace_GPER_illustr(0.9,1)
####### model 2
Ytrain<-Xtrain%*%betac2 + (pnorm(Xtrain[,7]+Xtrain[,8]+Xtrain[,9]))*rnorm(n,0,sig)
#################################################################################
trace_GPER_illustr(0.5,2)
trace_GPER_illustr(0.9,2)
#######COGPER for model 2
trace_CoGPER_illustr <- function(taux,model){
  bs <- sqrt(as.integer(as.numeric(table(group))))
  cv <- cv.cogper(x=Xtrain,y=Ytrain,group=group,method="GLasso",tau=taux,pf.scale = 0.5*bs)
  beta=t(cv$cogper.fit$beta)
  seqLambdaGL=cv$lambda
  matplot(seqLambdaGL,beta[,cc1], type = "l",col = 3,lty = 1,ylim=xlm,lwd=1,ylab="Coefficients",
          main=expression(paste("COGPER   ",tau,"=0.5")),xlab = expression(lambda))
  matlines(seqLambdaGL,beta[,cc2], type = "l",col = 2,lty = 1,lwd=1)
  matlines(seqLambdaGL,beta[,cc3], type = "l",col = 4,lty = 1,lwd=1)
  matlines(seqLambdaGL,beta[,cc4], type = "l",col = 1,lty = 1,lwd=1)
  text(0.5,0.5,expression("G"[3]),col=4,cex=1)
  abline(v=cv$lambda.min,lty=2)
  theta=t(cv$cogper.fit$theta)
  seqLambdaGL=cv$lambda
  matplot(seqLambdaGL,theta[,cc1], type = "l",col = 3,lty = 1,ylim=xlm1,lwd=1,ylab="Coefficients",
          main=expression(paste("COGPER   ",tau,"=0.5")),xlab = expression(lambda))
  matlines(seqLambdaGL,theta[,cc2], type = "l",col = 2,lty = 1,lwd=1)
  matlines(seqLambdaGL,theta[,cc3], type = "l",col = 4,lty = 1,lwd=1)
  matlines(seqLambdaGL,theta[,cc4], type = "l",col = 1,lty = 1,lwd=1)
  text(0.5,0.5,expression("G"[3]),col=4,cex=1)
  abline(v=cv$lambda.min,lty=2)
}
par(mfrow = c(2, 2))
trace_CoGPER_illustr(0.5,2)
trace_CoGPER_illustr(0.9,2)
```
